### ISSUE TITLE
Create Account subclasses

### ISSUE THREAD

**Issue by AidenMartinAiden** [Ash530888/Mentor-Matching#4]
- [x] User
- [x] AdministrativeAccount

**Comment by Ash530888** [comment]
I wasn't sure of how the sendMessageToUser method in User should work.

**Comment by AidenMartinAiden** [comment]
Hmm, that's a good point that I haven't thought about. We could say that User has an array of messages as a field, create a new Message class, sendMessage and receiveMessage method. So:

1. user1 wants to send message to user2
2. user1 types a string in gui
3. gui sends the string to user1 class, which calls sendMessage(messageString, user2)
4. in sendMessage, user2.receiveMessage(messageString) is called
5. user2 adds the messageString to its internal message array to do so.
